server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tempvs_user
    username: postgres
    password: pass
app:
  base-url: http://localhost:8080
authorization:
  token: security_token
email:
  service:
    url: ${EMAIL_SERVICE_URL:localhost:8081}
