server:
  port: 8088
spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/tempvs_user}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
app:
  base-url: http://localhost:8080
authorization:
  token: security_token
email:
  service:
    url: ${EMAIL_SERVICE_URL:localhost:8081}
