spring:
  liquibase:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
authorization:
  token: security_token
app:
  base-url: http://localhost:8080
zonky:
  test:
    database:
      postgres:
        docker:
          image: postgres:18.2
